### ISSUE TITLE
Type error when trying to find tracks

### ISSUE THREAD

**Issue by BachoSeven** [taurheim/scrobblify#35]
Will mention that I'm using the extended streaming history files (endsong*.json) format

```
TypeError: Cannot read properties of undefined (reading 'split')
    at app.add15da1.js:1:18496
    at Array.map (<anonymous>)
    at t.value (app.add15da1.js:1:18461)
    at o.<anonymous> (app.add15da1.js:1:21179)
    at u (chunk-vendors.dfc867f9.js:215:55074)
    at Generator._invoke (chunk-vendors.dfc867f9.js:215:56400)
    at Generator.e.<computed> [as next] (chunk-vendors.dfc867f9.js:215:55496)
    at tt (app.add15da1.js:1:20036)
    at o (app.add15da1.js:1:20239)
    at app.add15da1.js:1:20300
    at new Promise (<anonymous>)
    at o.<anonymous> (app.add15da1.js:1:20180)
    at o.e (app.add15da1.js:1:23773)
    at nt (chunk-vendors.dfc867f9.js:67:11644)
    at o.n (chunk-vendors.dfc867f9.js:67:13456)
    at nt (chunk-vendors.dfc867f9.js:67:11644)
    at o.On.e.$emit (chunk-vendors.dfc867f9.js:67:26452)
    at o.click (chunk-vendors.dfc867f9.js:460:2566)
    at nt (chunk-vendors.dfc867f9.js:67:11644)
    at HTMLButtonElement.n (chunk-vendors.dfc867f9.js:67:13456)
    at HTMLButtonElement.Qr.a._wrapper (chunk-vendors.dfc867f9.js:67:51712)
rt @ chunk-vendors.dfc867f9.js:sourcemap:67
```

**Comment by taurheim** [comment]
Fixed in commit 5ffe8c8 — the app now fully supports Spotify Extended Streaming History (endsong*.json) files. The parser handles missing metadata fields (e.g. artist name) gracefully, preventing the TypeError on .split().
